### ISSUE TITLE
#11 still present.... :(

### ISSUE THREAD

**Issue by hyllm** [quietvoid/hdr10plus_parser#14] opened 2020-01-19 14:05 UTC
![72661527-77473d80-39db-11ea-9551-46613727e001](https://user-images.githubusercontent.com/33330694/72682408-0d0ec580-3acd-11ea-9031-8f0b8142cb7b.png)

**Comment by quietvoid** [comment] 2020-01-19 15:35
Sample?

**Comment by hyllm** [comment] 2020-01-19 18:59
sample is the same as when opening issue #10

**Comment by quietvoid** [comment] 2020-01-19 22:46
Looking into it.

**Comment by wswartzendruber** [comment] 2020-01-22 20:32
I'm getting the same thing with _Alita: Battle Angel_ (UPC 0-24543-52017-7-80).

**Comment by jojo54000** [comment] 2020-01-24 12:15
I can also confirm these errors on file Alita: Battle Angel and it chapter 2...
But no error on alita with v0.2.5 ??

**Comment by jojo54000** [comment] 2020-01-24 12:19
other question: are the generated json files currently reliable or can they be improved further?
I gave it a try: I re-encoded an hdr10 + video with x265 (without the --dhdr10-opt nor --hdr10-opt option), and I regenerated a json file on this re-encoded file. result: the 2 json files (that of the original video and that re-encoded) are different ?? when they should logically be identical since no optimization has been made by x265? I do not understand.

**Comment by quietvoid** [comment] 2020-01-24 18:52
Reencoding with x265 has metadata mismatches at metadata changes (scene changes), which result in 1-2 SEI messages being placed differently compared to the input JSON.

The last version (0.2.6)  is not reliable, there is a logic flaw that breaks the parsing of the SEI bytes.
I've looked into it but no clear solution yet.

**Comment by jojo54000** [comment] 2020-01-24 20:10
These mismatches created by x265 should be seen as something normal or this is a "bug" in x265 ?
Why v0.2.5 works best on alita movie ?

**Comment by hyllm** [comment] 2020-01-28 12:55
yes... 0.2.5 work on alita, but change profile A to profile B after encpde... don't know what that means... 0.2.4 works too and leaves as profile A after encode

**Comment by NZDivinity** [comment] 2020-01-28 14:51
> yes... 0.2.5 work on alita, but change profile A to profile B after encpde... don't know what that means... 0.2.4 works too and leaves as profile A after encode

Same error on Dark Phoenix with 0.2.6 sadly. 
0.2.5 extracts JSON without error, but the profile changes from A to B after encoding also. 
Assuming 0.2.4 works the same as for Alita, whilst retaining the original profile, would the resulting metadata JSON be missing out on anything that 0.2.6 has?

**Comment by quietvoid** [comment] 2020-01-28 15:07
There has to be a compromise. I've explained the changing profiles in #13 
I still don't know what the profiles mean, but there is no missing metadata.

As for the 0.2.6 issue, I haven't had the time to try and fix it again yet. There is undefined behaviour depending on the metadata used for x265 tests, which sometimes work for some cases but not for others. No idea how to differentiate the cases yet.

**Comment by jojo54000** [comment] 2020-01-28 15:25
"It'll take some time but I don't want to compromise the fidelity of the parsed values, like 0.2.4 does."
So do not use 0.2.4 ? Keep 0.2.6 for now ?

**Comment by quietvoid** [comment] 2020-01-28 15:30
0.2.6 is more likely to crash when parsing, 0.2.4 might not crash but some MaxScl values may be wrong.

**Comment by jojo54000** [comment] 2020-01-29 07:54
"0.2.4 might not crash but some MaxScl values may be wrong."
a lot of values?
the re-encoded video will not be faithful to the original?

**Comment by quietvoid** [comment] 2020-01-29 11:59
Only values under 8 and over 65536 would be likely wrong. Both of which appear in It: Chapter Two.

**Comment by hyllm** [comment] 2020-01-31 18:41
It: Chapter 2 cannot be parsed at all.. :( crashing with all versions.. :(

**Comment by cocimho** [comment] 2020-02-02 16:27
I have the same error : 
![image](https://user-images.githubusercontent.com/57756974/73611333-39eccd80-45e1-11ea-9c6c-f8b0073cd2ac.png)
Please can u help ?

thx

**Comment by hyllm** [comment] 2020-02-02 16:47
just wait for fix. quietvoid is aware of it. :)

**Comment by cocimho** [comment] 2020-02-02 20:23
> just wait for fix. quietvoid is aware of it. :)

Oh ok just great !! Sorry for disturb !
Hope he’ll find a solution :-)

**Comment by jojo54000** [comment] 2020-02-03 08:04
for now, use madvr with its dynamic hdr, which is close to hdr10 + (you have to read it directly on your pc with mpc be for example)

**Comment by hyllm** [comment] 2020-02-04 07:52
for now usage is like this:

try 0.2.6, if don't crash, you have correct metadata... otherwise, try 0.2.5, you'll get correct results, don't mind changing profile A to B... if you don't like the profile change, go for 0.2.4, but you can get wrong metadata...

I am correct?

**Comment by GG44000** [comment] 2020-02-07 19:22
I come to give you a test report:
It Chapter 2 (Profile B)=0.2.6, 0.2.5, 0.2.4 no creation of json. 0.2.3 json create (profile A) but crash x265
American gangster (Profile B)=0.2.6 no creation of json. 0.2.5, 0.2.4 json create but crash x265
Abominable (Profile B)=0.2.6 no creation of json. 0.2.5 json create and x265 ok at profile B
Doctor Sleep (Profile B)=0.2.6, 0.2.5, 0.2.4 no creation of json. 0.2.3 json create but crash x265
Stuber (Profile A)= 0.2.4, 0.2.3 json create and x265 ok at profile A
Dark phoenix (Profile A)= 0.2.4 0.2.3 json create and x265 at profile A

**Comment by quietvoid** [comment] 2020-02-08 05:02
Okay, I think I've got it fixed.
Can you guys test this binary, before I make a new release: [hdr10plus_parser_bugfix_windows_x86_64.zip](https://github.com/quietvoid/hdr10plus_parser/files/4173806/hdr10plus_parser_bugfix_windows_x86_64.zip)

I still have to validate the source against the reencoded metadata.

**Comment by hyllm** [comment] 2020-02-08 08:28
alita: battle angel still the same error. :( going to try IT:CH2

**Comment by hyllm** [comment] 2020-02-08 08:44
ok.. IT:CH2 extracted without error. Going to try encode.

**Comment by NZDivinity** [comment] 2020-02-08 09:01
> Okay, I think I've got it fixed.
> Can you guys test this binary, before I make a new release: [hdr10plus_parser_bugfix_windows_x86_64.zip](https://github.com/quietvoid/hdr10plus_parser/files/4173806/hdr10plus_parser_bugfix_windows_x86_64.zip)
> 
> I still have to validate the source against the reencoded metadata.
> 
> As for the different profiles, I may or may not look into it further.

Issue unfortunately persists with Dark Phoenix, json extraction fails :/

**Comment by quietvoid** [comment] 2020-02-08 13:08
Thanks, weird that tests pass but previously working title fail.
Looking into both.

**Comment by quietvoid** [comment] 2020-02-08 23:32
All right, this version seems to work with Alita: Battle Angel and Dark Phoenix.
Please try: [hdr10plus_parser_bugfix2_windows_x86_64.zip](https://github.com/quietvoid/hdr10plus_parser/files/4175596/hdr10plus_parser_bugfix2_windows_x86_64.zip)

If you have more titles, it could be useful to test if they still get parsed.
I have other tests to do first to make sure the metadata is correct.

**Comment by hyllm** [comment] 2020-02-08 23:42
bugfix2 successfully extracted Alita:BA and It:CH2... I don't have Dark Phoenix disc.

**Comment by NZDivinity** [comment] 2020-02-09 05:55
Both Dark Phoenix(Profile A) and Doctor Sleep(Profile B) extract successfully :)

Don't suppose you know what the difference is between Profile A and Profile B, and if anything is lost when the profiles change from A to B when encoded?

Thanks again

**Comment by jojo54000** [comment] 2020-02-09 12:59
i found this in a forum:
"HDR10+ is very similar to DV in that you do your grade with your reference monitor and then do the analysis. But, HDR10+ uses 9 statistical precentile bands (1%, 25%, 50%, 75%, 90%, 95%, 99.98% plus 2 special parameters called llc) for image analysis and has 9 bezier curves for mapping to other displays from the master reference. The key point to HDR10+ is the Profile A and B json. Profile B is the selection you should normally use as it contains all the image statistical data and bezier curve information."
So, profile B contains more informations than profile A (bezier curve information), but i don't know how hdr10+parser manages to create this additional information from profile A (according to my tests, profile A is always converted to profile B with hdr10 + parser, to be confirmed ...), since bezier curve information is not present in profile A ?
logically, it's normal to always get profile B with this software because since v0.2.5, bezier curve info are always added (see changelog), but how "invent" this information from profile A ??

**Comment by quietvoid** [comment] 2020-02-09 14:19
There's a crucial misunderstanding of what I said. There is no bezier curve info being created out of nowhere.
Simply, when there is no bezier curve, the fields are still added to the JSON. However these added fields are all empty.
It looks like this:
> 
      "BezierCurveData": {
        "Anchors": [],
        "KneePointX": 0,
        "KneePointY": 0
      },

**Comment by jojo54000** [comment] 2020-02-09 17:07
Thank you for your clear explanations.
So, if I understand correctly, it is completely normal to obtain a profile B by injecting the metadata extracted with the x265 encoder.
"However this point is useful: has 9 bezier curves for mapping to other displays from the master reference
Profile A titles don't seem to have a targeted display luminance (it is 0) that the curve could map to, so I could keep Profile A."
In the end, this is just a detail and converting to profile B is enough, am I wrong?
In any case, your version looks stable on the titles tested.

**Comment by quietvoid** [comment] 2020-02-09 21:29
Thanks, it seems that my assumption is correct for Profile A titles. I've fixed it so that reencoding stays Profile A.

I'll have a new version soon, there still seems to be issues with incorrect data parsed.

**Comment by hyllm** [comment] 2020-02-11 11:15
> 
> 
> Thanks, it seems that my assumption is correct for Profile A titles. I've fixed it so that reencoding stays Profile A.
> 
> I'll have a new version soon, there still seems to be issues with incorrect data parsed.

THANK YOU FOR YOUR GREAT WORK!!! Getting donations???

**Comment by quietvoid** [comment] 2020-02-13 01:51
No, I do not accept donations.

I have release version 0.2.7 that should fix this issue for now.
Please test and let me know.

**Comment by quietvoid** [comment] 2020-02-21 22:57
Closing this as all the sources mentioned are parsed correctly.

**Closed by quietvoid** 2020-02-21 22:57 UTC
